name: Terraform CI

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  terraform:
    name: Terraform Validate, Format, Plan, Security
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Terraform Format Check
        run: terraform fmt -check -recursive

      - name: Terraform Init & Validate (root module)
        run: |
          terraform init
          terraform validate

      - name: Terraform Init & Validate (example)
        working-directory: examples/basic
        run: |
          terraform init
          terraform validate

      - name: Terraform Plan (example)
        working-directory: examples/basic
        run: terraform plan -no-color

      - name: Run Checkov (root module)
        uses: bridgecrewio/checkov-action@v12
        with:
          directory: .
          quiet: true
          soft_fail: true

      - name: Run Checkov (example)
        uses: bridgecrewio/checkov-action@v12
        with:
          directory: examples/basic
          quiet: true
          soft_fail: true
